Joystream/hydra

substrate-query-framework/cli/src/generate/ModelRenderer.ts
This PR fixes `reserved word` error for FieldResolvers. 
Example, lets say you an entity named `Class` then the field resolver will look like this: 
```ts
@FieldResolver(() => Property)
async properties(@Root() class: Class): Promise<Property[]> {}
```
so the root argument name is a reserved ts/js word.
=> cli: set root argument name to 'r' for FieldResolver

substrate-query-framework/cli/src/templates/entities/model.ts.mst
This PR adds `constructor` to warthog model template. Passing objects to model constructor during initialization will be possible now:
```ts
const user = new User({ username: 'joe' })
db.save(user)
```
=> Add constructor to model template

substrate-query-framework/index-builder/src/migrations/CreateSchema.ts
This PR adds an index on `substrate_event.block_number` for improved performance.
=> Add index to substrate_event table

substrate-query-framework/cli/src/parse/WarthogModelBuilder.ts, substrate-query-framework/cli/src/parse/constant.ts, substrate-query-framework/cli/test/fixtures/explicit-id-field.graphql, substrate-query-framework/cli/test/helpers/ExplicitIdField.test.ts
This PR allows defining `id: ID!` field in the input schema and removes it before generating warthog model classes. We are removing the `id` field from models because warthog `codegen` command fails when there is a field named id in the model class.
=> cli: allow explicit id field in the input schema

substrate-query-framework/cli/package.json, substrate-query-framework/cli/src/templates/entities/resolver.ts.mst, substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
This PR adds required pagination object definitions to the resolver template https://github.com/Joystream/joystream/issues/1350
Note: pagination feature works with this release [warthogv2.19](https://github.com/metmirr/warthog/releases/tag/v2.19)
=> Add required pagination object definitions to resolver template

substrate-query-framework/e2e-tests/docker-compose.yml, substrate-query-framework/e2e-tests/run-tests.sh, substrate-query-framework/e2e-tests/schema/Dockerfile, substrate-query-framework/index-builder/CHANGELOG.md, substrate-query-framework/index-builder/package.json, substrate-query-framework/index-builder/src/entities/SubstrateEventEntity.ts, substrate-query-framework/index-builder/src/indexer/BlockProducer.ts, substrate-query-framework/index-builder/src/indexer/IndexerStatusService.ts, substrate-query-framework/index-builder/src/node/QueryNode.ts, substrate-query-framework/index-builder/src/processor/MappingsProcessor.ts, substrate-query-framework/index-server/src/modules/indexer-status/indexer-status.service.ts
After https://github.com/Joystream/hydra/pull/79 and https://github.com/Joystream/hydra/pull/76
This PR adds small bugfixes and improvements:
- No error is thrown when the indexer head is not published to redis. Instead. -1 is return
- The processor waits until the indexer head becomes non-negative
- Complete blocks cache expiration is renewed after it is accessed
- Prior to running e2e-tests, all the docker images (including indexer-api-gateway) are built afresh
=> Hydra builder 0.0.17-alpha

substrate-query-framework/e2e-tests/docker-compose.yml, substrate-query-framework/e2e-tests/run-tests.sh, substrate-query-framework/e2e-tests/schema/Dockerfile, substrate-query-framework/index-builder/Dockerfile, substrate-query-framework/index-builder/src/indexer/BlockProducer.ts, substrate-query-framework/index-builder/src/indexer/IBlockProducer.ts, substrate-query-framework/index-builder/src/indexer/IndexerStatusService.ts, substrate-query-framework/index-builder/src/indexer/RedisRelayer.ts, substrate-query-framework/index-builder/src/indexer/redis-keys.ts, substrate-query-framework/index-builder/test/integration/status-service.test.ts, substrate-query-framework/index-server/src/modules/indexer-status/indexer-status.resolver.ts, substrate-query-framework/index-server/src/modules/indexer-status/indexer-status.service.ts
After https://github.com/Joystream/hydra/pull/80
IndexerStatusService adds the following properties to Redis:
- HEAD (Indexer Head block)
- LAST_COMPLETE (last indexed block height)
- MAX_COMPLETE (maximal height of a complete block) 
- CHAIN_HEIGHT (last block height from the chain)
The properties above are available for querying using the indexerStatus GraphQL query in indexer-api-gateway
=> Add LAST_COMPLETE, MAX_COMPLETE, CHAIN_HEIGHT to Indexer status

substrate-query-framework/cli/src/generate/field-context.ts, substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
This PR resolves 'numeric values are sent in hex format to the GraphQL clients' issue.
=> fix numeric value hex representation

substrate-query-framework/cli/src/generate/utils.ts, substrate-query-framework/cli/src/templates/entities/resolver.ts.mst
esolvers returns null instead of throwing an error when the property is not resolved
=> bugfix: #115

substrate-query-framework/cli/package.json, substrate-query-framework/cli/src/generate/RelationshipGenerator.ts, substrate-query-framework/cli/src/helpers/relations.ts, substrate-query-framework/cli/src/model/Relation.ts, substrate-query-framework/cli/src/templates/entities/model.ts.mst, substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
This PR sets the`nullable` option based on the field nullable option, if the field is not required the option is set to `true`.
It depends on [warthog v2.22.0](https://github.com/metmirr/warthog/releases/tag/v2.22.0)
_Note: during the review, `substrate-query-framework/cli/src/generate/RelationshipGenerator.ts` file can be ignored. The changes come from formatting._
=> Set nullable option true for relation decorators

substrate-query-framework/cli/src/templates/entities/resolver.ts.mst, substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
This PR adds a resolver to the `resolver.mst` template to query a single entity by unique where input (e.g `id`), at the moment one can fetch a list of entities.
```graphql
query {
channel(where: { id: "1" }) {
id
handle
}
}
```
=> Add single entity query to resolver template

substrate-query-framework/cli/src/templates/entities/resolver.ts.mst, substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
This PR replaces warthog service `findOne` method with typeorm's entity manager `findOne`. 
When querying entities on https://hydra.joystream.org/graphql I notice there is an error when if the queried entity exists for example:
```graphql
query {
channel(where: { id: "82" }) {
id
handle
}
}
{
"errors": [
{
"message": "Cannot return null for non-nullable field Channel.handle.",
...
}
```
After debugging locally I notice that calling `this.service.findOne` generates a wrong SQL query, for the above graphql query it generates the following SQL query:
```sql
SELECT "channel"."id" AS "channel_id" FROM "channel" "channel" WHERE "channel"."id" = $1 AND "channel"."deleted_at" IS NULL LIMIT 20 -- PARAMETERS: ["1"]
```
So the query only returns the entity id all the other fields are missing.
I have …
=> Replace warthog's findOne with typeorm's manager.findOne

substrate-query-framework/index-builder/CHANGELOG.md, substrate-query-framework/index-builder/package.json, substrate-query-framework/index-builder/src/indexer/BlockProducer.ts, substrate-query-framework/index-builder/src/indexer/FIFOCache.test.ts, substrate-query-framework/index-builder/src/indexer/FIFOCache.ts, substrate-query-framework/index-builder/src/indexer/indexer-consts.ts
This is a more serious attempt to address the issue of non-final (and reorged) blocks being indexed by the indexer. 
- Once we get a new finaleased header from the API subscription, it is stored in an in-memory cache
- When the pipeline requests a block at a given height, the indexer 
- if there is a cached header for the request height, get it
- if not, wait until the required height is sufficiently behind the current chain height (the threshold is controlled by `FINALITY_THRESHOLD` env variable.
=> Indexer cached finilazed headers

.eslintrc.js, packages/hydra-indexer/package.json, packages/hydra-indexer/src/indexer/BlockProducer.ts, packages/hydra-indexer/src/indexer/FIFOCache.test.ts, packages/hydra-indexer/src/indexer/FIFOCache.ts, packages/hydra-indexer/src/indexer/indexer-consts.ts
Indexer watches only finalized heads. The headers of the finalized blocks are cached.
=> indexer caches finalized heads

packages/hydra-indexer/src/db/ormconfig.ts, packages/hydra-indexer/src/migrations/BlockTimestamp.ts
This PR adds a migration class in order to add `block_timestamp` column to the indexer database (if there is anyone who runs indexer before we add support for `block_timestamp` then they would need to run indexer database migrations). When `BlockTimestamp` migration is run against an existing indexer database then the default value for `block_timestamp` will be set to `0`.
=> hydra-indexer: add block timestamp database migration

packages/hydra-e2e-tests/docker-compose.yml, packages/hydra-indexer-gateway/generated/binding.ts, packages/hydra-indexer-gateway/generated/classes.ts, packages/hydra-indexer-gateway/generated/schema.graphql, packages/hydra-indexer-gateway/package.json, packages/hydra-indexer-gateway/src/modules/substrate-event/substrate-event.model.ts, packages/hydra-indexer/CHANGELOG.md, packages/hydra-indexer/Dockerfile, packages/hydra-indexer/package.json, packages/hydra-indexer/src/db/ormconfig.ts, packages/hydra-indexer/src/entities/SubstrateEventEntity.ts, packages/hydra-indexer/src/migrations/BlockTimestamp1607690267560.ts, packages/hydra-indexer/src/migrations/EventExtraFields1612537639000.ts, packages/hydra-indexer/src/migrations/ExtrinsicName1612537537000.ts, packages/hydra-indexer/src/migrations/IndexerSchema1601637366082.ts, packages/hydra-indexer/src/run.ts, yarn.lock
This PR adds additional fields to the indexer:
- extrinsicArgs
- extrinsicHash
- data with event params
This eg enables queries of the form 
```gql
query {
substrateEvents(limit: 5, orderBy: blockNumber_DESC, where: {name_eq: "balances.Transfer", data_json: { param2: { value_gt: 15283400000}}}) {
name
extrinsicName
extrinsicArgs
extrinsicHash
data
} 
}
```
=> Add extrinsicArgs, extrinsicHash and JSON data field for the indexer Substrate event

docs/install-hydra.md
There are currently known issues with running the hydra-cli on Windows so I have added "unix based operating system" as one of the system requirements.
=> adding unix based opperating system to the list of prerequisits

packages/hydra-cli/src/utils/utils.ts
It adds error handling for graphql errors by parsing warthog's `codegen` stderr.
=> Parse warthog codegen stderr for graphql errors

packages/hydra-cli/src/templates/scaffold/.dockerignore, packages/hydra-cli/src/templates/scaffold/README.md, packages/hydra-cli/src/templates/scaffold/docker-compose.yml, packages/hydra-cli/src/templates/scaffold/docker/Dockerfile.builder, packages/hydra-cli/src/templates/scaffold/package.json.mst
Minor fixes and improvements for hydra-cli scaffold:
- copy all json files in Dockerfile.builder (so that type defs are always copied)
- use nohoist and separate yarn install for mappings 
- docker-compose env variable fixes 
- add .dockerignore
=> hydra-cli scaffold fixes

packages/hydra-cli/src/generate/ModelRenderer.ts, packages/hydra-cli/src/generate/VariantsRenderer.ts, packages/hydra-cli/src/templates/entities/model.ts.mst, packages/hydra-cli/src/templates/variants/variants.mst, packages/hydra-cli/test/helpers/ModelRenderer.test.ts, packages/hydra-cli/test/helpers/VariantsRenderer.test.ts
It fixes importing the same variant twice and missing `bn.js` module import.
=> Variant import fix

packages/hydra-cli/src/codegen/WarthogWrapper.ts, packages/hydra-cli/src/templates/graphql-server/tsconfig.json.mst, packages/hydra-cli/src/templates/graphql-server/warthog.env.yml, packages/hydra-cli/src/templates/scaffold/package.json.mst, packages/hydra-e2e-tests/Dockerfile, packages/hydra-e2e-tests/docker-compose.yml
Adds the necessary env variables to warthog `env.yml` so that in the production mode the transpiled js files are used.
=> fix(hydra-cli): use transpiled js files for query-node 

packages/hydra-cli/src/templates/entities/resolver.ts.mst, packages/hydra-cli/src/templates/graphql-server/tsconfig.json.mst, packages/hydra-cli/test/helpers/ModelRenderer.test.ts
This PR 
- enables the `declaration: true` flag for `generated/graphql-server/tsconfig.json` for successful compilation
- fixes duplicate function name issue: when entity name is uncountable there will be two functions with the same name e.g `VideoMediaMetadata`. The issue is fixed by adding an additional `*ByUniqueInput` at the end of the type name for the unique query resolver.
=> Graphql server bug fixes

packages/hydra-cli/src/templates/scaffold/schema.graphql, packages/hydra-e2e-tests/docker-compose.yml, packages/hydra-e2e-tests/fixtures/manifest.yml, packages/hydra-e2e-tests/fixtures/schema.graphql, packages/hydra-e2e-tests/fixtures/typedefs.json, packages/hydra-e2e-tests/package.json, packages/hydra-e2e-tests/run-tests.sh, packages/hydra-e2e-tests/test/e2e/api/substrate-api.ts, packages/hydra-e2e-tests/test/e2e/api/typeRegistry.ts, packages/hydra-indexer/package.json, packages/hydra-indexer/src/entities/SubstrateEventEntity.ts, packages/hydra-indexer/src/model/QueryEvent.ts, packages/hydra-typegen/package.json, packages/hydra-typegen/src/metadata/metadata.ts, packages/sample/mappings/package.json, packages/sample/mappings/yarn.lock, packages/sample/yarn.lock, yarn.lock
as stated in the title...
affects: hydra-e2e-tests, @dzlzv/hydra-indexer, @dzlzv/hydra-typegen, sample, sample-mappings
=> feat(packages): upgrade polkadot/api version to 4.2.1

packages/hydra-cli/src/generate/SourcesGenerator.ts, packages/hydra-cli/src/templates/entities/model-all.ts.mst, packages/hydra-cli/test/helpers/model-index-context.test.ts
import from `../src/modules/`  instead of copying the model files
=> fix(hydra-cli): fix single import of model files

packages/hydra-cli/src/templates/scaffold/mappings/mappings.ts, packages/hydra-e2e-tests/fixtures/mappings/mappings.ts, packages/hydra-typegen/src/generators/helpers.spec.ts, packages/hydra-typegen/src/generators/helpers.ts, packages/hydra-typegen/src/metadata/default-types.ts, packages/hydra-typegen/src/metadata/metadata.ts, packages/hydra-typegen/src/templates/module.hbs, packages/hydra-typegen/src/util.ts, packages/sample/mappings/mappings.ts, yarn.lock
Fixes https://github.com/Joystream/hydra/issues/336
The typed events generated by typegen should now will look like 
```
get params(): [Type1, Type2, Type3] {
return [ createType('Type1', ...), createType('Type2', ...), createType('Type3', ...)]
}
```
This fixes some bugs and inconveniences related to the naming based on the types.
=> feat(typegen): tuple return type for event.params

packages/hydra-processor/src/ingest/GraphQLSource.ts, packages/hydra-processor/src/ingest/IProcessorSource.ts, packages/hydra-processor/src/ingest/index.ts, packages/hydra-processor/src/process/MappingsProcessor.ts, packages/hydra-processor/src/queue/EventQueue.ts, packages/hydra-processor/src/start/ProcessorRunner.ts, packages/hydra-processor/src/start/config.ts, packages/hydra-processor/src/start/manifest.ts, packages/hydra-processor/src/state/IStateKeeper.ts, packages/hydra-processor/src/state/StateKeeper.ts, packages/hydra-processor/src/state/version.ts, packages/hydra-processor/src/util/utils.ts, packages/sample/.env, packages/sample/README.md, packages/sample/package.json, yarn.lock
This PR:
- checks version compatibility between Hydra Indexer and Hydra Processor
- improves performance by waiting until new blocks are produced by the indexer
- minor fixes for `sample` yarn scripts
=> Hydra processor check version

packages/hydra-e2e-tests/fixtures/manifest.yml, packages/hydra-e2e-tests/test/e2e/hooks.test.ts, packages/hydra-processor/src/executor/MappingsLookupService.ts, packages/hydra-processor/src/ingest/GraphQLSource.ts, packages/hydra-processor/src/ingest/IProcessorSource.ts, packages/hydra-processor/src/process/MappingsProcessor.ts, packages/hydra-processor/src/queue/BlockQueue.spec.ts, packages/hydra-processor/src/queue/BlockQueue.ts, packages/hydra-processor/src/queue/IBlockQueue.ts, packages/hydra-processor/src/queue/index.ts, packages/hydra-processor/src/start/config.ts, packages/hydra-processor/src/start/manifest.ts, packages/hydra-processor/src/state/StateKeeper.ts, packages/hydra-processor/src/util/index.ts, packages/hydra-processor/src/util/ranges.spec.ts, packages/hydra-processor/src/util/ranges.ts, packages/hydra-processor/src/util/utils.ts
Previously, block hooks were executed only for blocks for which there is at least one event handler. In particular, it was impossible to add an initialization hook to the genesis block, as there are no events there and thus it was always skipped. This PR fixes this, giving full control over the heights where the block hooks are executed
=> Hooks without events

packages/hydra-indexer/src/entities/SubstrateEventEntity.ts
Extrinsic args JSON was coerced to an empty string vs null, causing deserialization issues (#393)
affects: @dzlzv/hydra-indexer
ISSUES CLOSED: #393
=> fix(hydra-indexer): do not coerce null to empty string 

packages/hydra-typegen/src/generators/helpers.spec.ts, packages/hydra-typegen/src/generators/helpers.ts
affects: @dzlzv/hydra-typegen
tuples of the form (T1, T2, T3) are recursively replaced with [T1,T2,T3] & Codec
ISSUES CLOSED: #398
=> fix(hydra-typegen): do proper handling of tuples in typegen

packages/hydra-cli/src/generate/ModelRenderer.ts, packages/hydra-cli/src/generate/field-context.ts, packages/hydra-cli/src/generate/utils.ts, packages/hydra-cli/src/model/Field.ts, packages/hydra-cli/src/model/ObjectType.ts, packages/hydra-cli/src/model/relations.ts, packages/hydra-cli/src/parse/WarthogModelBuilder.ts, packages/hydra-cli/src/templates/entities/model.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/WarthogBaseService.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/index.ts.mst, packages/hydra-cli/src/templates/interfaces/resolver.ts.mst, packages/hydra-cli/src/templates/interfaces/service.ts.mst, packages/hydra-cli/test/fixtures/interfaces.graphql, packages/hydra-cli/test/helpers/Interfaces.test.ts, packages/hydra-cli/test/helpers/ModelRenderer.test.ts, packages/hydra-cli/test/helpers/Relationships.test.ts, packages/hydra-cli/test/helpers/WarthogModel.test.ts, packages/hydra-cli/test/helpers/model-index-context.test.ts, packages/hydra-e2e-tests/fixtures/manifest.yml, packages/hydra-e2e-tests/fixtures/mappings/index.ts, packages/hydra-e2e-tests/fixtures/mappings/loaders.ts, packages/hydra-e2e-tests/fixtures/schema.graphql, packages/hydra-e2e-tests/run-tests.sh, packages/hydra-e2e-tests/test/e2e/api/graphql-queries.ts, packages/hydra-e2e-tests/test/e2e/api/processor-api.ts, packages/hydra-e2e-tests/test/e2e/interfaces-e2e.test.ts, packages/hydra-e2e-tests/test/e2e/transfer-e2e.test.ts
A fully reworked implementation of the interfaces service with minimal dependency on the code
generation. First, IDs are fetched from a union of each implementation table satisfying the filter,
and afterwards each table is queried separately by those IDs.
fix(hydra-cli): add TYPEORM_LOGGING option to the graphql-server
test(hydra-e2e-test): add e2e tests for interface queries
affects: hydra-e2e-tests
=> fix(hydra-cli): fetch interface relations by default

packages/hydra-e2e-tests/test/e2e/api/graphql-queries.ts, packages/hydra-e2e-tests/test/e2e/api/processor-api.ts, packages/hydra-e2e-tests/test/e2e/transfer-e2e.test.ts, packages/hydra-processor/src/executor/TransactionalExecutor.ts
… by default
affects: hydra-e2e-tests, @joystream/hydra-processor
ISSUES CLOSED: #400
=> fix(hydra-processor): set createdAt, updatedAt to the block timestamp

package.json, packages/hydra-e2e-tests/package.json
There was an issue when running the following commands after freshly pulling repository resulted in error:
```
yarn
yarn workspace @joystream/hydra-processor build
yarn workspace @joystream/hydra-processor test # this will cause error because dependency - hydra-common is not built
```
The same was happening when running e2e tests, etc. because dependencies like `hydra-common` and `hydra-db-utils` are not built at that moment.
This PR adds a command to build all repositories - `yarn build`. It also renames `hydra-e2e-tests` -> `@joystream/hydra-e2e-tests`  to be consistent with other repo names.
=> Command for building all packages

.github/workflows/docker-publish.yml, .github/workflows/hydra-e2e-tests.yml, .github/workflows/hydra-unit-tests.yml, .github/workflows/publish.yml, package.json, packages/hydra-e2e-tests/package.json, packages/hydra-e2e-tests/test/e2e/api/substrate-api.ts, packages/hydra-indexer-gateway/package.json, packages/hydra-indexer/package.json, packages/hydra-typegen/package.json, yarn.lock
- bumps polkadot version to 4.15.1 to support parachain types 
- separate docker:tag yarn targets
=> fix(hydra-indexer): bump polkadot/api to 4.15.1

.github/workflows/docker-publish.yml, .github/workflows/hydra-e2e-tests.yml, .github/workflows/hydra-unit-tests.yml, .github/workflows/publish.yml, package.json, packages/hydra-e2e-tests/package.json, packages/hydra-e2e-tests/test/e2e/api/substrate-api.ts, packages/hydra-indexer-gateway/package.json, packages/hydra-indexer/package.json, packages/hydra-typegen/package.json, yarn.lock
- bumps polkadot version to 4.15.1 to support parachain types
- separate docker:tag yarn targets
=> fix(hydra-indexer): bump polkadot/api to 4.15.1 #431

README.md
It was a bit confusing jumping over repos to see one thing or the other :)
related: Is the hydra documentation, currently on https://dzhelezov.gitbook.io/hydra, reachable from joystream.org? It could be updated too within this PR.
=> docs: fix Sample project link

package.json, packages/bn-typeorm/package.json, packages/hydra-cli/package.json, packages/hydra-cli/src/templates/graphql-server/src/index.ts.mst, packages/hydra-cli/src/templates/graphql-server/tsconfig.json.mst, packages/hydra-cli/src/templates/scaffold/mappings/package.json.mst, packages/hydra-cli/src/templates/textsearch/service.ts.mst, packages/hydra-common/package.json, packages/hydra-db-utils/package.json, packages/hydra-e2e-tests/package.json, packages/hydra-indexer-gateway/package.json, packages/hydra-indexer/package.json, packages/hydra-processor/package.json, packages/hydra-processor/src/db/subscribers.ts, packages/hydra-processor/tsconfig.json, packages/hydra-typegen/package.json, packages/hydra-typegen/src/generators/helpers.spec.ts, packages/hydra-typegen/src/generators/helpers.ts, packages/hydra-typegen/src/metadata/metadata.ts, packages/sample/mappings/package.json, yarn.lock
Following a related PR in `Joystream/warthog`: https://github.com/Joystream/warthog/pull/7
**Note that `warthog` dependency needs to be updated after the new version is released!**
Scope:
- Fix `sanitizeNullCharacter` function: https://github.com/Joystream/hydra/commit/3d6abc5e9f0870ca31f8bb21110410ab7af0f55e
- Graphql-server TS4 compatibility (https://github.com/Joystream/hydra/commit/d16fb4f52eaabad5f95c1bade939963f8df02fb1)
- Enable warthog playground config via ENV (https://github.com/Joystream/hydra/commit/33305793c155b68efaf750f576ee42da1391912f)
- Fix search queries relationship filtering (https://github.com/Joystream/hydra/commit/52fc3de893b1fa1c74a0928a9112ba6f11e30337)
- `hydra-typegen` compatibility with TS4 (https://github.com/Joystream/hydra/commit/532a0c4a446cfca203a30b93a0c4 …
=> Fixes based on Olympia/Giza workarounds

packages/hydra-cli/package.json, packages/hydra-cli/src/codegen/WarthogWrapper.ts, packages/hydra-cli/src/templates/graphql-server/src/index.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/queryTemplates.ts.mst, packages/hydra-indexer-gateway/package.json, yarn.lock
Adds query templates support for GraphQL playground and updates Warthog.
Includes improvements from https://github.com/Joystream/warthog/pull/9 and https://github.com/Joystream/warthog/pull/10 .
=> Query templates support for GraphQL playground

packages/hydra-cli/src/templates/entities/model.ts.mst
Fixes a badly written condition merged in #479
=> feat: nullable variant support II

packages/hydra-cli/src/templates/entities/resolver.ts.mst
This PR adds support for querying variant fields in `*Connection` (pagination) queries. Previously, the `*Connection` resolver treated the variant field (to be queried) as a relation and thus skipped it while querying the entity from DB.
After this PR is merged, https://github.com/Joystream/joystream/issues/3381 would be resolved.
___
The connection resolver gets [fields](https://github.com/Joystream/hydra/blob/0aeecd7a2e655ae40adca687689ff44f3df5fd9f/packages/hydra-cli/src/templates/entities/resolver.ts.mst#L119) to be queried in the form of objects. To be exact (for `ownedNftConnection` query) as:
```javascript
{
edges: {
node: {
transactionalStatus: [Object],
metadata: {},
creatorRoyalty: {},
transactionalStatusAuction: [Object]
}
}
} 
```
As seen above, 
scalar fields exists as: …
=> added support for querying variant fields in *Connection (pagination) queries

packages/hydra-processor/src/executor/TransactionalExecutor.ts
Fixes issues described in https://github.com/Joystream/joystream/issues/3573
affects: @joystream/hydra-processor
These predicates are true in JS/TS:
```
const predicates = [
'0' < 'a',
'a' > 'A',
'b' > 'B',
'a' < 'b',
'A' < 'b'
]
console.log(predicates)
// [true, true, true, true]
That means the order of characters in JS/TS is
0, 1, 2, ... , 9, A, B, C, ..., Z, a, b, c, ..., z
```
The same predicates yield different results in Postgres:
```
SELECT
'0' < 'a',
'a' > 'A',
'b' > 'B',
'a' < 'b',
'A' < 'b',
version(); -- let's see Postgres version
-- t, f, f, t, t, PostgreSQL 12.10 (Debian 12.10-1.pgdg110+1)
That means the order of characters in Postgres is
0, 1, 2, ... , 9, a, A, b, B, C, c ..., Z, z
Plus, when I run the same query in an online sandbox at …
```
=> fix: processor's deterministic ids alphabet update

packages/hydra-cli/src/templates/entities/resolver.ts.mst
=> fix: change property name from 'nodes' to 'node' in reslovers template file

packages/hydra-cli/package.json, packages/hydra-indexer-gateway/package.json, yarn.lock
Updates prettier version. This helps to prevent an error during codegen in Joystream/Hydra that would need to be otherwise prevented by overwriting the dependency version.
Incorporates new GraphQL Playground and Warthog https://github.com/Joystream/graphql-playground/pull/3, https://github.com/Joystream/warthog/pull/15.
affects: @joystream/hydra-cli, @joystream/hydra-indexer-gateway
=> feat: prettier and warthog dependencies update

packages/hydra-processor/src/executor/EntityIdGenerator.ts, packages/hydra-processor/src/executor/TransactionalExecutor.ts, packages/hydra-processor/src/executor/index.ts
Changes argument of `generateNextId` to be usable in the mappings (outside of Hydra). Related to https://github.com/Joystream/hydra/pull/498.
affects: @joystream/hydra-processor
=> feat: deterministic id generator - utilities exposure fix

packages/hydra-cli/src/codegen/WarthogWrapper.ts, packages/hydra-cli/src/templates/graphql-server/src/index.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/processor.resolver.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/processorStateApp.ts.mst, packages/hydra-cli/src/templates/graphql-server/src/pubsub.ts.mst, packages/hydra-e2e-tests/docker-compose.yml, packages/hydra-processor/package.json, packages/hydra-processor/src/start/config.ts, packages/hydra-processor/src/state/StateKeeper.ts, yarn.lock
Send updates to `stateSubscription` independently from `processed_events_log_update` table updates.
This is achieved by introducing a new api endpoint `/update-processor-state` in the graphql server, to which (only) the processor can send updates that are then sent from the graphql server to all subscribers.
Processor will send updates to this endpoint (`STATE_UPDATE_ENDPOINT`) on each `ProcessorEvents.PROCESSED_EVENT` and `ProcessorEvents.STATE_CHANGE`.
Can be tested here: https://github.com/Joystream/joystream/pull/4413
=> stateSubscription: Send updates independently from 'processed_events_log_update' table

packages/hydra-typegen/src/templates/module.hbs
In [module.hbs](https://github.com/Joystream/hydra/blob/e2156b800b242f215e9196e123dc511c88019e01/packages/hydra-typegen/src/templates/module.hbs#L3) file in `hydra-typegen` package, there is an unused Codex import as: `import { Codec } from "@polkadot/types/types";`. This template file is being used to generate Events classes for each module inside `query-node/mappings/generated/types/`. The problem is if any event contains a param which is of codex type, then `Codec` is imported again, which leads to duplicate imports error while building the QN.
For example, in https://github.com/Joystream/joystream/pull/4517 the type of optional payment parameter in the MemberRemarked event is `Option<[AccountId32, u128] & Codec>`
Remove unused `Codec` import from the template file.
affects: …
=> fix: remove 'Codec' import from template files in generated/types dir

.github/workflows/bump.yml, .github/workflows/docker-publish.yml, .github/workflows/publish.yml
see -> https://github.com/Joystream/hydra/actions/runs/4600283498
logs from the failed Github Action:
=> fix: update CI checks runner to latest ubuntu due to failing jobs

packages/hydra-cli/src/templates/graphql-server/src/processorStateApp.ts.mst, packages/hydra-processor/src/queue/BlockQueue.ts
Fixes https://github.com/Joystream/hydra/issues/519
`blocksWithEvents` `AsyncGenerator` was not properly awaiting the promise returned by `pWaitFor`. This promise was supposed to stop the generator from yeilding next block until all evens emitted in that block were fetched from the indexer.
Becasue it was not properly awaited, it was possible for the `blocksWithEvents` to yeild a block with an incomplete array of events in case the indexer was responsing to requests more slowly than usual.
As a result, the processor would think it processed a full block and update the `last_scanned_block` value in the database, while not actually processing all events from that block. This is the scenario that has caused issues such as https://github.com/Joystream/hydra/issues/519
=> Processor syncing fix (`blocksWithEvents`)

.github/workflows/hydra-e2e-tests.yml, packages/hydra-cli/src/codegen/WarthogWrapper.ts, packages/hydra-cli/src/templates/scaffold/manifest.yml, packages/hydra-e2e-tests/docker-compose.yml, packages/hydra-e2e-tests/fixtures/manifest.yml, packages/hydra-e2e-tests/fixtures/mappings/mappings.ts, packages/hydra-processor/test/fixtures/manifest.yml, packages/hydra-typegen/package.json, packages/sample/manifest.yml
Fix Hydra e2e test by updating Hydra-CLI scaffold (`@types/lodash` issue discovered in: https://github.com/Joystream/hydra/pull/518#pullrequestreview-1367100147) and the test fixtures
affects: @joystream/hydra-cli, @joystream/hydra-e2e-tests, @joystream/hydra-typegen
=> Fix Hydra e2e test

.github/workflows/hydra-unit-tests.yml, packages/hydra-e2e-tests/run-tests.sh, packages/hydra-e2e-tests/test/e2e/api/substrate-api.ts, packages/hydra-processor/docker-compose-test.yml, packages/hydra-processor/package.json, packages/hydra-processor/src/queue/BlockQueue.ts, packages/hydra-processor/src/state/StateKeeper.ts, packages/hydra-processor/test/api/substrate-api.ts, yarn.lock
Fixes the way events are polled from the queue by `blocksWithEvents` AsynGenerator.
Prevents the processor from getting stuck if the number of events in a block exceeds the max. event queue size.
Issue originally discovered here: https://github.com/Joystream/joystream/pull/4731#issuecomment-1500154353
I tested the scenario that originally caused the error and the issue appears to be resolved, while the fix for https://github.com/Joystream/hydra/issues/519 continues to work properly.
=> fix(fix event polling): fix event polling

packages/hydra-typegen/src/commands/typegen/index.ts, packages/hydra-typegen/src/metadata/extract.ts, packages/hydra-typegen/src/metadata/types.ts
addresses https://github.com/Joystream/joystream/issues/4877
based on #527
=> Fix `hydra-typegen` to properly generate types for deprecated/deleted events & extrinsics

packages/hydra-indexer/src/substrate/SubstrateService.ts, packages/hydra-indexer/src/substrate/index.ts
Fixes #533 
affects: @joystream/hydra-indexer
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1204404358291458/1205679208614424) by [Unito](https://www.unito.io)
=> Reconnect to node on runtime upgrade
