Joystream/hydra

- substrate-query-framework/index-builder/package.json
- substrate-query-framework/index-builder/src/bootstrap/Bootstrapper.ts
- substrate-query-framework/index-builder/src/db/helper.ts
- substrate-query-framework/index-builder/src/entities/SubstrateEventEntity.ts
- substrate-query-framework/index-builder/src/index.ts
- substrate-query-framework/index-builder/src/indexer/IndexerStatusService.ts
- substrate-query-framework/index-builder/src/indexer/index.ts
- substrate-query-framework/index-builder/src/interfaces/json-types.ts
- substrate-query-framework/index-builder/src/model/substrate-interfaces.ts
- substrate-query-framework/index-builder/src/node/QueryNodeManager.ts
- substrate-query-framework/index-builder/src/node/QueryNodeStartOptions.ts
- substrate-query-framework/index-builder/src/processor/DBSource.ts
- substrate-query-framework/index-builder/src/processor/GraphQLSource.ts
- substrate-query-framework/index-builder/src/processor/HandlerLookupService.ts
- substrate-query-framework/index-builder/src/processor/IProcessorSource.ts
- substrate-query-framework/index-builder/src/processor/MappingsProcessor.ts
- substrate-query-framework/index-builder/src/processor/index.ts
- substrate-query-framework/index-builder/yarn.lock
- substrate-query-framework/index-server/.dockerignore
- substrate-query-framework/index-server/Dockerfile
- substrate-query-framework/index-server/package.json
- substrate-query-framework/index-server/src/index.ts
- substrate-query-framework/index-server/src/logger.ts
- substrate-query-framework/index-server/src/modules/substrate-event/substrate-event.resolver.ts
- substrate-query-framework/index-server/src/modules/substrate-event/substrate-event.service.ts
- substrate-query-framework/index-server/src/modules/substrate-extrinsic/substrate-extrinsic.model.ts
- substrate-query-framework/index-server/yarn.lock
Implementation of GraphQLSource for event ingestion. The processor uses a GraphQL indexer endpoint to fetch events and extrinsics;
> Processor api sourcing 2

- substrate-query-framework/cli/src/templates/indexer.package.json
- substrate-query-framework/index-builder/CHANGELOG.md
- substrate-query-framework/index-builder/package.json
- substrate-query-framework/index-server/package.json
- substrate-query-framework/index-server/yarn.lock
This PR updates the indexer references with the latest release of index-builder
> Update index-builder references to 0.0.14-alpha.1

- substrate-query-framework/cli/CHANGELOG.md
- substrate-query-framework/cli/package.json
- substrate-query-framework/cli/src/commands/scaffold.ts
- substrate-query-framework/cli/src/templates/scaffold/.env
New release of hydra-cli
- JSON type definition support
- Dockerfile
> Hydra-cli 0.0.14 release

- substrate-query-framework/index-builder/CHANGELOG.md
- substrate-query-framework/index-builder/package.json
- substrate-query-framework/index-builder/src/indexer/BlockProducer.ts
- substrate-query-framework/index-builder/src/indexer/indexer-consts.ts
- substrate-query-framework/index-builder/src/processor/MappingsProcessor.ts
- substrate-query-framework/index-builder/src/processor/processor-consts.ts
0.0.16 release of hydra-builder-lib
- Timeout if there are now new blocks for a specified number of times
- All the upstream changes merged into master after 0.0.15-alpha.2
> Hydra builder 0.0.16-alpha release

- substrate-query-framework/index-builder/CHANGELOG.md
- substrate-query-framework/index-builder/package.json
- substrate-query-framework/index-builder/src/node/QueryNode.ts
- substrate-query-framework/index-server/src/modules/indexer-status/indexer-status.service.ts
> hydra-indexer-lib 0.0.18-alpha release

- substrate-query-framework/cli/CHANGELOG.md
- substrate-query-framework/cli/package.json
- substrate-query-framework/cli/src/helpers/WarthogWrapper.ts
- substrate-query-framework/cli/yarn.lock
- Bump warthog fork version to 2.20.0
> Hydra-cli release 0.0.17

- substrate-query-framework/e2e-tests/test/e2e/api/processor-api.ts
> fix e2e-test

- .github/workflows/hydra-e2e-tests.yml
- substrate-query-framework/e2e-tests/package.json
- substrate-query-framework/e2e-tests/run-tests.sh
- substrate-query-framework/e2e-tests/scripts/db.sh
> Add github workflows

- substrate-query-framework/cli/src/commands/codegen.ts
- substrate-query-framework/cli/src/helpers/WarthogWrapper.ts
> add --no-install flag to hydra-cli codegen to skip yarn install

- substrate-query-framework/cli/CHANGELOG.md
- substrate-query-framework/cli/package.json
- substrate-query-framework/cli/src/generate/utils.ts
- substrate-query-framework/cli/src/templates/entities/resolver.ts.mst
> Hydra cli 0.0.20

- substrate-query-framework/cli/package.json
- substrate-query-framework/cli/src/generate/utils.ts
- substrate-query-framework/cli/src/templates/entities/resolver.ts.mst
- substrate-query-framework/cli/test/helpers/ModelRenderer.test.ts
- substrate-query-framework/cli/yarn.lock
> bugfix #112: proper pluralization for batch and connection queries

- docs/README.md
- packages/hydra-cli/package.json
- packages/hydra-cli/src/templates/scaffold/docker-compose.yml
- packages/hydra-processor/package.json
- Docs update 
- Version bump
- Fix hydra-processor/templates location
> Update docs for v1 and bump versions

- .github/workflows/hydra-cli-release.yml
- .github/workflows/hydra-e2e-tests.yml
- .github/workflows/hydra-unit-tests.yml
> add release workflow for hydra-cli

- .github/workflows/hydra-cli-release.yml
- .github/workflows/hydra-e2e-tests.yml
- .github/workflows/hydra-unit-tests.yml
> Release workflow

- packages/hydra-indexer/src/indexer/BlockProducer.ts
As stated. At startup, the indexer waits for the chain height instead fo throwing an error
> [hydra-indexer] If the start block is ahead of chain, wait vs throw

- packages/hydra-cli/src/codegen/WarthogWrapper.ts
- packages/hydra-cli/src/commands/preview.ts
Resolves https://github.com/Joystream/hydra/issues/182
> Bugfix: hydra cli api preview

- .vscode/launch.json
- packages/apps-config/package.json
- packages/hydra-typegen/package.json
- packages/hydra-typegen/src/commands/typegen/index.ts
- packages/hydra-typegen/src/generators/imports-registry.ts
- packages/hydra-typegen/src/helpers/parse-yaml.ts
- packages/hydra-typegen/src/metadata/extract.ts
- packages/hydra-typegen/src/util.ts
- packages/hydra-typegen/test/config.yml
- yarn.lock
Use YML file along with cli flags for typegen runs.
Example:
```yml
metadata:
source: wss://kusama-rpc.polkadot.io
blockHash: '0x45eb7ddd324361adadd4f8cfafadbfb7e0a26393a70a70e5bee6204fc46af62e'
events:
- Balances.Transfer
calls:
- Balances.transfer
outDir: ./generated
```
> [hydra-typegen] and yml config support

- packages/hydra-processor/.prettierrc.js
- packages/hydra-processor/package.json
- packages/hydra-processor/src/db/dal.ts
- packages/hydra-processor/src/prometheus/ProcessorPromClient.ts
- packages/hydra-processor/src/prometheus/server.ts
- packages/hydra-processor/src/start/ProcessorOptions.ts
- packages/hydra-processor/src/start/QueryEventProcessingPack.ts
- packages/hydra-processor/src/start/manifest.spec.ts
- packages/hydra-processor/src/start/manifest.ts
- packages/hydra-processor/src/state/IProcessorStateHandler.ts
- packages/hydra-processor/src/util/log.ts
- packages/hydra-processor/src/util/utils.ts
- packages/hydra-processor/test/fixtures/manifest.yml
- packages/hydra-processor/test/fixtures/test-mappings.ts
- packages/hydra-processor/test/manifest.spec.ts
- packages/hydra-processor/test/tsconfig.json
- packages/hydra-processor/tsconfig.json
- yarn.lock
This is a PR for https://github.com/orgs/Joystream/projects/32#card-53368865
It is a part of a bigger project of defining the Hydra processor pipeline via manifest file. This PR is for review purposes only and will be incorporated in upstream PRs once the work is complete.
> [hydra-processor]  parse and validate manifest file

- docs/install-hydra.md
- docs/mappings/README.md
- docs/schema-spec/README.md
- docs/schema-spec/entities.md
- docs/schema-spec/enums.md
- docs/schema-spec/full-text-queries.md
- docs/schema-spec/the-query-goodies.md
- Fixing some small  spelling and grammar mistakes
- Adding some alternative commands for windows users. 
- Fixing a couple of errors in the code examples
> Updating documentation

- packages/hydra-cli/package.json
This reverts commit fabf17e6bf0c78ba62dbff4da463f5640d143433.
> Revert "test version bump (#227)"

- .github/workflows/hydra-cli-release.yml
- .github/workflows/hydra-e2e-tests.yml
- .github/workflows/hydra-unit-tests.yml
- packages/hydra-cli/package.json
> Revert "Ci test"

- packages/hydra-cli/package.json
- packages/sample/package.json
Bump warthog fork (fixes issues #209  #210)
> fix(hydra-cli) bump warthog to v2.23.0 (#209 #210)

- packages/hydra-cli/src/codegen/WarthogWrapper.ts
- packages/hydra-cli/src/utils/utils.ts
Fixes https://github.com/Joystream/hydra/issues/56
> [hydra-cli] throw error if warthog codegen fail

- examples/indexers/README.md
- examples/indexers/node-template/README.md
- examples/indexers/node-template/docker-compose.yml
- add `examples/indexers`
- add node-template indexer example
> docs(examples): add node-template indexer example

- packages/hydra-indexer-gateway/src/index.ts
- packages/hydra-indexer-gateway/src/modules/indexer-status/indexer-status.resolver.ts
- packages/hydra-indexer-gateway/src/modules/indexer-status/indexer-status.service.ts
- packages/hydra-indexer-gateway/src/version.ts
affects: @dzlzv/hydra-indexer-gateway
> add 'inSync' and 'hydraVersion' to the indexerStatus query

- packages/hydra-db-utils/package.json
affects: @dzlzv/hydra-db-utils
> fix(hydra-db-utils): build and /lib reference in package.json

- packages/hydra-cli/src/generate/RelationshipGenerator.ts
- packages/hydra-cli/src/model/Relation.ts
- packages/hydra-cli/src/model/index.ts
- packages/hydra-cli/src/model/relations.ts
- packages/hydra-cli/test/helpers/Relationships.test.ts
It fixes overriding relation type which causes having wrong relation type. Also, it refactors the relationship generator and add more tests.
> Bug fix and refactoring

- packages/hydra-cli/src/generate/ModelRenderer.ts
- packages/hydra-cli/test/helpers/ModelRenderer.test.ts
> fix(hydra-cli): templating fixes

- packages/hydra-processor/src/ingest/GraphQLSource.ts
- packages/hydra-processor/src/process/MappingsProcessor.ts
- packages/hydra-processor/src/prometheus/ProcessorPromClient.ts
- packages/hydra-processor/src/prometheus/server.ts
- packages/hydra-processor/src/start/config.ts
- packages/hydra-processor/src/state/ProcessorStateHandler.ts
affects: @dzlzv/hydra-processor
> fix(hydra-processor): lazily init config to fix the --indexer flag

- packages/hydra-cli/src/parse/FTSDirective.ts
- packages/hydra-cli/src/parse/SchemaParser.ts
- packages/hydra-cli/test/helpers/SchemaParser.test.ts
fixes https://github.com/Joystream/hydra/issues/368 and adds a test
> fix(hydra-cli): fix stack overflow caused by lodash.cloneDeep

- packages/hydra-cli/src/templates/scaffold/mappings/mappings.ts
- packages/hydra-cli/src/templates/scaffold/schema.graphql
> fix(hydra-cli): update scaffold templates

- .github/workflows/bump.yml
- packages/hydra-processor/package.json
- yarn.lock
affects: @dzlzv/hydra-processor
> fix(hydra-processor): fix missing dependency in hydra-procesor

- packages/hydra-typegen/src/metadata/events.spec.ts
- packages/hydra-typegen/src/metadata/extract.ts
affects: @dzlzv/hydra-typegen
ISSUES CLOSED: #373
> fix(hydra-typegen): fix tuple types not correctly parsed by typegen

- Dockerfile
- docs/paginate-query-results.md
- docs/queries.md
- docs/sort-query-results.md
- package.json
- packages/hydra-cli/Dockerfile
- packages/hydra-cli/package.json
- packages/hydra-cli/src/templates/scaffold/docker/Dockerfile.builder
- packages/hydra-cli/src/templates/scaffold/docker/Dockerfile.processor
- packages/hydra-cli/src/templates/scaffold/docker/Dockerfile.query-node
- packages/hydra-indexer-gateway/Dockerfile
- packages/hydra-indexer-gateway/package.json
- packages/hydra-indexer/Dockerfile
- packages/hydra-indexer/package.json
Node v12 -> Node v14
hydra-cli: Docker templates
hydra-indexer, hydra-indexer-gateway: Dockerfile images
> Node 14 upgrade

- packages/hydra-indexer/src/entities/SubstrateExtrinsicEntity.ts
> Do not coerce null value to an empty string

- packages/hydra-cli/src/templates/scaffold/docker-compose-indexer.yml
> fix(hydra-cli): add DB env variables to indexer docker-compose stack

- .eslintrc.js
- hydra-indexer.md
- package.json
- packages/hydra-cli/README.md
- packages/hydra-cli/src/generate/SourcesGenerator.ts
- packages/hydra-cli/src/generate/utils.ts
- packages/hydra-cli/src/templates/graphql-server/src/utils.ts.mst
- packages/hydra-indexer/src/entities/SubstrateBlockEntity.ts
- packages/hydra-indexer/src/entities/SubstrateEventEntity.ts
- packages/hydra-indexer/src/entities/SubstrateExtrinsicEntity.ts
- packages/hydra-indexer/src/indexer/BlockProducer.ts
- packages/hydra-indexer/src/indexer/IBlockProducer.ts
- packages/hydra-indexer/src/indexer/IndexBuilder.ts
- packages/hydra-indexer/src/model/QueryEventBlock.ts
- packages/hydra-indexer/src/node/config.ts
- packages/hydra-indexer/src/redis/RedisRelayer.ts
- packages/hydra-indexer/src/status-service/IStatusService.ts
- packages/hydra-indexer/src/substrate/ISubstrateService.ts
- packages/hydra-indexer/src/substrate/timestamp.ts
- packages/hydra-typegen/README.md
- yarn.lock
affects: @dzlzv/hydra-cli, @dzlzv/hydra-indexer, @dzlzv/hydra-typegen
> docs(hydra-processor): annotate code

- packages/hydra-cli/src/generate/constants.ts
- packages/hydra-cli/src/generate/field-context.ts
- packages/hydra-cli/src/templates/variants/variants.mst
- packages/hydra-cli/test/helpers/VariantsRenderer.test.ts
- packages/hydra-cli/test/helpers/WarthogModel.test.ts
- packages/hydra-e2e-tests/fixtures/mappings/mappings.ts
- packages/hydra-e2e-tests/fixtures/schema.graphql
- yarn.lock
affects: @joystream/hydra-cli, hydra-e2e-tests
> fix(hydra-cli): render variant fields of array type

- packages/hydra-cli/src/generate/field-context.ts
- packages/hydra-cli/src/model/Field.ts
- packages/hydra-cli/src/templates/variants/variants.mst
- packages/hydra-e2e-tests/fixtures/mappings/loaders.ts
- packages/hydra-e2e-tests/fixtures/schema.graphql
- packages/hydra-e2e-tests/run-tests.sh
- packages/hydra-e2e-tests/test/e2e/api/graphql-queries.ts
- packages/hydra-e2e-tests/test/e2e/arrayfields-e2e.test.ts
affects: @joystream/hydra-cli, @joystream/hydra-e2e-tests
> fix(hydra-cli): fix array fields

- packages/hydra-cli/src/codegen/WarthogWrapper.ts
- packages/hydra-cli/src/commands/scaffold.ts
- packages/hydra-cli/src/templates/scaffold/package.json.mst
> fix: hydra CLI scaffold improvements

- packages/hydra-cli/package.json
- yarn.lock
Fixes #452. Brings a patch made for Subsquid's Warthog repo into Joystream repositories.
> fix: loadManyToMany undefined fix

- packages/hydra-db-utils/package.json
- packages/hydra-indexer/package.json
- packages/hydra-processor/package.json
- packages/hydra-processor/src/executor/TransactionalExecutor.ts
- yarn.lock
Addresses https://github.com/Joystream/hydra/issues/399
> Generate deterministic entity ids, remove shortId

- packages/hydra-cli/src/templates/entities/model.ts.mst
Fixes https://github.com/Joystream/hydra/issues/434
> feat: nullable variant support

- packages/hydra-cli/src/templates/entities/resolver.ts.mst
> fix: fixed *Connection (pagination) queries resolver

- .github/workflows/bump.yml
- .github/workflows/docker-publish.yml
- .github/workflows/hydra-e2e-tests.yml
- .github/workflows/hydra-unit-tests.yml
- .github/workflows/publish.yml
Updates used Github actions versions. Fixes https://github.com/Joystream/hydra/issues/468
> feat: github actions dependencies version update

- packages/hydra-cli/src/templates/entities/resolver.ts.mst
> fix: accept array of orderBy args for *connection queries

- packages/hydra-cli/src/generate/constants.ts
- packages/hydra-cli/src/templates/variants/variants.mst
- packages/hydra-cli/test/helpers/VariantsRenderer.test.ts
> fix: variant input schema -> output schema inconsistency
